version: '3.8'

services:
  batchservice:
    build:
      context: .
      dockerfile: DockerFile-batchservice
    ports:
      - "8080:8080"
    environment:
      - APP_HOST=${APP_HOST}
      - APP_PORT=${APP_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - redis
    networks:
      - mynetwork

  redis:
    image: redis:7.4-bookworm
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
