version: '3.8'

services:
  batchservice:
    build:
      context: .
      dockerfile: DockerFile-batchservice
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - mynetwork

  redis:
    image: redis:7.4-bookworm
    ports:
      - "6380:6379"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
