FROM golang:1.23 as builder

WORKDIR /app

# RUN git clone https://github.com/mbroughani81/lambda-bc-opt .
COPY . .

RUN ls -la && sleep 5

RUN cd lambda-bc-opt && \
    go build -o BatchService batchservice/main.go && \
    mv BatchService ../deploy && \
    cd ..

# Final image
FROM debian:bookworm-slim

WORKDIR /app/deploy

COPY --from=builder /app/deploy/BatchService /app/deploy/

RUN chmod +x BatchService

CMD ["./BatchService"]
