FROM golang:1.23 as builder

WORKDIR /app

RUN git clone https://github.com/mbroughani81/lambda-bc-opt .

# RUN ls -la && sleep 20

RUN cd lambda-bc-opt && \
    go build -o BatchService batchservice/main.go && \
    mv BatchService ../deploy && \
    cd ../deploy

# Final image
FROM debian:bullseye-slim

WORKDIR /app/deploy

COPY --from=builder /deploy/BatchService /app/deploy/

RUN chmod +x BatchService

CMD ["./BatchService"]

